### ISSUE TITLE
ZeroDivisionError: integer division or modulo by zeroが返ってくる

### ISSUE THREAD

**Issue by TaiseiHigashiyama** [musyoku/wavenet#5]
質問失礼します。wavenetの超初心者です。
トレーニングの「python train.py -w wav --lr 0.00001」を実行した結果、ZeroDivisionError: integer division or modulo by zeroが返ってきました。これを解決するためにはいったいどうすれば良いのでしょうか？
また、サンプルを作成した結果ノイズだけのものが生成されました。こちらもどうすれば解消するのでしょうか？

**Comment by musyoku** [comment]
こんにちは
ZeroDivisionErrorの発生箇所はどこでしょうか？
またChainerのバージョンを教えてください

**Comment by TaiseiHigashiyama** [comment]
返信ありがとうございます。
発生箇所は
Traceback (most recent call last):
  File "train.py", line 120, in <module>
    main()
  File "train.py", line 112, in main
    average_loss /= len(files)
ZeroDivisionError: integer division or modulo by zeroです。
Chainerのバージョンは1.24です

**Comment by musyoku** [comment]
おそらくlen(files)が0になっていると思われるので、wavディレクトリに音声ファイルが存在していない可能性があります

**Comment by TaiseiHigashiyama** [comment]
なるほど!!
そのwavディレクトリは/train_audio/wavのことでよろしいでしょうか？
また、wavであれば音声ファイルは何でもよろしいのでしょうか？

**Comment by musyoku** [comment]
-wオプションで指定したディレクトリですのでこの場合は/train_audio/wavになります。
wav形式であれば何でもかまいません。
wavenetは学習に時間がかかるので、初めは短いテストデータで検証することをおすすめします。

**Comment by TaiseiHigashiyama** [comment]
了解です。
丁寧な解説ありがとうございました!!
