### ISSUE TITLE
AttributeError: 'module' object has no attribute 'using_config'

### ISSUE THREAD

**Issue by TaiseiHigashiyama** [musyoku/wavenet#6]
こんにちは。
今回はwavenet-master/train_audio/wavにyoutubeからダウンロードした.wavをいれてpython train.py を実行したところ
loading dre.wav
receptive field width: 32 [millisecond]
receptive field width: 256 [step]
files: 1 batch_size: 16 train_width: 500
Traceback (most recent call last):
  File "train.py", line 139, in <module>
    main()
  File "train.py", line 126, in main
    repeat=500
  File "train.py", line 55, in train_audio
    with chainer.using_config("train", True):
AttributeError: 'module' object has no attribute 'using_config'
というエラーが吐き出されました。このエラーの原因は一体何なのでしょうか？

**Comment by musyoku** [comment]
おそらくChainerのバージョン1にusing_configがないことが原因だと思います。
Chainerのバージョンを2にするか、`with chainer.using_config("train", True):`の行を削除すると動くと思います。

**Comment by TaiseiHigashiyama** [comment]
返信ありがとうございます!!おかげさまで実行することが出来ました。
そこで3つほど質問なのですが、①train_audio/train.pyを実行することで何が起こるんですか？②train_audo/generate.pyを実行してもノイズしかない音声が生成されるのですが原因は何でしょうか？また、生成される音声をファミマの入店音から変えるにはどうすればよいのでしょうか？③_tests_の中にあるディレクトリや複数のgenerate.pyは何に使うのでしょか？
質問ばかりですみませんがよろしくお願いいたします。

**Comment by musyoku** [comment]
1. `train.py`は入力された音声信号列から次の時刻の信号を予測できるように学習するものです。
2. 学習が不十分な可能性があります。経験上lossがかなり小さく（0.001以下）ならないとうまく生成できませんでした。また用意した音声に無音部分があると、無音から無音を予測するモデルになってしまい、音声生成がうまくいかないケースがありました。できるだけ学習用の音声から無音部分を取り除く必要があります。他の方のTensorFlow実装などをみると、学習に用いた音声の冒頭部分をヒントとして与えて、その先を生成させる手法を用いているものがありましたが、おそらく無音から出発するとうまく生成できない場合があったのではないかと思います。私の実装では無音に相当する信号からスタートしてその先を生成していくものなので、学習に失敗していると無音状態から抜け出せず何も生成されない現象が起きます。
また生成される音声は学習に用いた音声によります。私の場合はファミマの入店音を使っただけで、別の音声を用意して学習させればその音声を生成できるようになります。
ファミマの入店音程度のごく短い音声の場合でも、GTX1080で数十分学習させないと生成できませんでした。
3. `_tests_`はデバッグ用に作ったものなので学習には使いません。
